<?php

use MODX\Revolution\modSystemSetting;
use MODX\Revolution\modX;
/**
 * System settings shipped with the modxMCP package (namespace "modxmcp").
 *
 * @var modX $modx
 * Returns an array of modSystemSetting objects keyed by setting key.
 *
 * On install the component is ENABLED (modxmcp.enabled = Yes) and the api_token is
 * auto-generated by resolve.token.php (visible in System Settings so it can be copied).
 * The endpoint is still protected by that random token. Filesystem root browsing is off.
 */
/* @var modX $modx */
$settings = array();

$defs = array(
    // key, value, xtype, area
    array('modxmcp.enabled', 1, 'combo-boolean', 'modxmcp:main'),
    array('modxmcp.api_token', '', 'textfield', 'modxmcp:main'),
    array('modxmcp.service_user_id', 0, 'textfield', 'modxmcp:main'),
    array('modxmcp.audit_log', 1, 'combo-boolean', 'modxmcp:main'),
    array('modxmcp.debug', 0, 'combo-boolean', 'modxmcp:main'),
    array('modxmcp.auto_static', 0, 'combo-boolean', 'modxmcp:main'),
    array('modxmcp.disabled_groups', 'versionx,virtualpage,minishop2,migx,access,property_sets,contexts,package_management,namespaces,lexicon', 'textfield', 'modxmcp:main'),
    array('modxmcp.allow_run_processor', 0, 'combo-boolean', 'modxmcp:security'),
    array('modxmcp.max_payload_bytes', 1048576, 'textfield', 'modxmcp:limits'),
    array('modxmcp.max_read_bytes', 262144, 'textfield', 'modxmcp:limits'),
    array('modxmcp.allow_root_filesystem_read', 0, 'combo-boolean', 'modxmcp:security'),
    array('modxmcp.require_https', 1, 'combo-boolean', 'modxmcp:security'),
    array('modxmcp.allowed_ips', '', 'textfield', 'modxmcp:security'),
    array('modxmcp.component_code_roots', 'core/components,assets/components', 'textfield', 'modxmcp:security'),
    array('modxmcp.core_path', '{core_path}components/modxmcp/', 'textfield', 'modxmcp:paths'),
);

foreach ($defs as $d) {
    /* @var modSystemSetting $setting */
    $setting = $modx->newObject(modSystemSetting::class);
    $setting->fromArray(array(
        'key' => $d[0],
        'value' => $d[1],
        'xtype' => $d[2],
        'namespace' => 'modxmcp',
        'area' => $d[3],
    ), '', true, true);
    $settings[$d[0]] = $setting;
}

unset($defs, $d);
return $settings;
