<?php
$_lang['modxmcp'] = 'MODX MCP';
$_lang['area_modxmcp_main'] = 'Основные';
$_lang['area_modxmcp_security'] = 'Безопасность';
$_lang['area_modxmcp_logging'] = 'Логирование';
$_lang['area_modxmcp_limits'] = 'Ограничения';
$_lang['area_modxmcp_paths'] = 'Пути';
$_lang['modxmcp_menu_desc'] = 'Статус MCP-эндпоинта и API-токен.';
$_lang['modxmcp_graph'] = 'Граф связей';
$_lang['modxmcp_graph_title'] = 'граф связей';
$_lang['modxmcp_graph_desc'] = 'Как связаны элементы сайта: что чем используется, битые ссылки, мёртвый код.';

$_lang['modxmcp_cmp_intro'] = 'MCP-эндпоинт этого MODX-сайта. Подключается к клиенту modx-mcp (задайте MODX_MCP_SITE_URL + MODX_MCP_TOKEN).';
$_lang['modxmcp_cmp_endpoint'] = 'Эндпоинт';
$_lang['modxmcp_cmp_enabled'] = 'Включён';
$_lang['modxmcp_cmp_yes'] = 'Да';
$_lang['modxmcp_cmp_no'] = 'Нет';
$_lang['modxmcp_cmp_enable_hint'] = 'поставьте modxmcp.enabled = Да для активации';
$_lang['modxmcp_cmp_token'] = 'API-токен';
$_lang['modxmcp_cmp_token_set'] = 'задан';
$_lang['modxmcp_cmp_token_notset'] = 'не задан — нажмите «Сгенерировать» ниже';
$_lang['modxmcp_cmp_auto_static'] = 'Авто-статика';
$_lang['modxmcp_cmp_audit_log'] = 'Журнал аудита';
$_lang['modxmcp_cmp_package_install'] = 'Установка пакетов';
$_lang['modxmcp_cmp_on'] = 'Вкл';
$_lang['modxmcp_cmp_off'] = 'Выкл';
$_lang['modxmcp_cmp_regenerate'] = 'Сгенерировать новый токен';
$_lang['modxmcp_cmp_new_token'] = 'Новый токен (скопируйте сейчас — показывается один раз):';
$_lang['modxmcp_cmp_settings_hint'] = 'Подробные настройки — в «Системные настройки», пространство имён modxmcp.';
$_lang['modxmcp_cmp_integrations'] = 'Интеграции';
$_lang['modxmcp_cmp_integrations_intro'] = 'Популярные дополнения, с которыми modxMCP умеет работать на этом сайте.';
$_lang['modxmcp_cmp_confirm_regenerate'] = 'Сгенерировать новый API-токен modxMCP? Текущие MCP-клиенты перестанут работать, пока вы не обновите MODX_MCP_TOKEN.';
$_lang['modxmcp_cmp_regenerate_failed'] = 'Не удалось сгенерировать токен. Проверьте журнал ошибок менеджера.';
