<?php
$_lang['modxmcp'] = 'MODX MCP';
$_lang['area_modxmcp_main'] = 'General';
$_lang['area_modxmcp_security'] = 'Security';
$_lang['area_modxmcp_logging'] = 'Logging';
$_lang['area_modxmcp_limits'] = 'Limits';
$_lang['area_modxmcp_paths'] = 'Paths';
$_lang['modxmcp_menu_desc'] = 'MCP endpoint status and API token.';
$_lang['modxmcp_graph'] = 'Dependency graph';
$_lang['modxmcp_graph_title'] = 'dependency graph';
$_lang['modxmcp_graph_desc'] = 'How the site is wired: what uses what, broken references, dead code.';

$_lang['modxmcp_cmp_intro'] = 'MCP endpoint for this MODX site. Pair it with the modx-mcp client (set MODX_MCP_SITE_URL + MODX_MCP_TOKEN).';
$_lang['modxmcp_cmp_endpoint'] = 'Endpoint';
$_lang['modxmcp_cmp_enabled'] = 'Enabled';
$_lang['modxmcp_cmp_yes'] = 'Yes';
$_lang['modxmcp_cmp_no'] = 'No';
$_lang['modxmcp_cmp_enable_hint'] = 'set modxmcp.enabled = Yes to activate';
$_lang['modxmcp_cmp_token'] = 'API token';
$_lang['modxmcp_cmp_token_set'] = 'set';
$_lang['modxmcp_cmp_token_notset'] = 'not set — click Regenerate below';
$_lang['modxmcp_cmp_auto_static'] = 'Auto-static';
$_lang['modxmcp_cmp_audit_log'] = 'Audit log';
$_lang['modxmcp_cmp_package_install'] = 'Package install';
$_lang['modxmcp_cmp_on'] = 'On';
$_lang['modxmcp_cmp_off'] = 'Off';
$_lang['modxmcp_cmp_regenerate'] = 'Regenerate API token';
$_lang['modxmcp_cmp_new_token'] = 'New token (copy it now — shown once):';
$_lang['modxmcp_cmp_settings_hint'] = 'Edit detailed behaviour under System → System Settings, namespace modxmcp.';
$_lang['modxmcp_cmp_integrations'] = 'Integrations';
$_lang['modxmcp_cmp_integrations_intro'] = 'Popular add-ons modxMCP can work with on this site.';
$_lang['modxmcp_cmp_confirm_regenerate'] = 'Regenerate the modxMCP API token? Existing MCP clients will stop working until you update MODX_MCP_TOKEN.';
$_lang['modxmcp_cmp_regenerate_failed'] = 'Failed to regenerate the token. Check the manager error log.';
